name: Deploy Fullstack

on:
  push:
    branches: [main, dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HEALTHCHECK_BACKEND: "http://${{ secrets.SERVER_HOST }}:8000/"
      HEALTHCHECK_FRONTEND: "http://${{ secrets.SERVER_HOST }}/"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend/genstoryai_frontend

      - name: Build frontend
        run: pnpm run build
        working-directory: ./frontend/genstoryai_frontend

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Ensure project path exists
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo mkdir -p ${{ secrets.SERVER_PROJECT_PATH }} && sudo chown -R ${{ secrets.SERVER_USER }}:${{ secrets.SERVER_USER }} ${{ secrets.SERVER_PROJECT_PATH }}"

      - name: Rsync deploy files to server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./backend/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PROJECT_PATH }}/backend/
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./frontend/genstoryai_frontend/dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PROJECT_PATH }}/frontend_dist/
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./Dockerfile ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PROJECT_PATH }}/
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./nginx.conf ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PROJECT_PATH }}/
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./supervisord.conf ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PROJECT_PATH }}/

      - name: Build and deploy on server (with backup)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd ${{ secrets.SERVER_PROJECT_PATH }} &&
            docker image tag genstoryai-fullstack:latest genstoryai-fullstack:last-success || true &&
            docker build -t genstoryai-fullstack:latest . &&
            docker stop genstoryai-fullstack || true && docker rm genstoryai-fullstack || true &&
            docker run -d --name genstoryai-fullstack -p 80:80 genstoryai-fullstack:latest
          "

      - name: Healthcheck Backend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "curl -fsSL --max-time 10 $HEALTHCHECK_BACKEND"

      - name: Healthcheck Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "curl -fsSL --max-time 10 $HEALTHCHECK_FRONTEND"

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Healthcheck failed, rolling back..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd ${{ secrets.SERVER_PROJECT_PATH }} &&
            docker stop genstoryai-fullstack || true && docker rm genstoryai-fullstack || true &&
            docker run -d --name genstoryai-fullstack -p 80:80 genstoryai-fullstack:last-success
          " 