name: Deploy Fullstack

on:
  push:
    branches: [main, dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HEALTHCHECK_BACKEND: "http://${{ secrets.SERVER_HOST }}/api/health"
      HEALTHCHECK_FRONTEND: "http://${{ secrets.SERVER_HOST }}/"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Ensure project path exists
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo mkdir -p ${{ secrets.SERVER_PROJECT_PATH }} && sudo chown -R ${{ secrets.SERVER_USER }}:${{ secrets.SERVER_USER }} ${{ secrets.SERVER_PROJECT_PATH }}"

      - name: Rsync all code to server
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude 'node_modules' \
            --exclude 'frontend/genstoryai_frontend/node_modules' \
            --exclude '.github' \
            --exclude '*.db' \
            --exclude '*.sqlite3' \
            --exclude 'db_data' \
            --exclude 'data' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PROJECT_PATH }}/

      - name: Update environment variables for production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd ${{ secrets.SERVER_PROJECT_PATH }} &&
            sed -i 's|http://localhost:80|http://${{ secrets.SERVER_HOST }}:80|g' docker-compose.yml &&
            sed -i 's|http://localhost|http://${{ secrets.SERVER_HOST }}|g' docker-compose.yml
          "

      - name: Build and deploy on server (with backup)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd ${{ secrets.SERVER_PROJECT_PATH }} &&
            docker image tag genstoryai-app:latest genstoryai-app:last-success || true &&
            docker build -t genstoryai-app:latest . &&
            docker stop genstoryai-app || true && docker rm genstoryai-app || true &&
            docker run -d --name genstoryai-app -p 80:80 genstoryai-app:latest
          "

      - name: Healthcheck Backend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "curl -fsSL --max-time 10 $HEALTHCHECK_BACKEND"

      - name: Healthcheck Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "curl -fsSL --max-time 10 $HEALTHCHECK_FRONTEND"

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Healthcheck failed, rolling back..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd ${{ secrets.SERVER_PROJECT_PATH }} &&
            docker stop genstoryai-app || true && docker rm genstoryai-app || true &&
            docker run -d --name genstoryai-app -p 80:80 genstoryai-app:last-success
          " 